TMP_DIR = "tmp"
OUT_DIR = "out"
URL = "https://www.mass.gov/doc/covid-19-raw-data-{}/download"
URL_DATE_FMT = "%B-%-d-%Y"
DAY_FMT = "%-m/%-d/%Y"
CITATION_DATE_FORMAT = "%B %-d, %Y"
STATISTICS_DAY_FMT = "%b %-d"

CITATION_URL = "https://www.mass.gov/doc/covid-19-dashboard-{}/download"
CITATION_TITLE = "COVID-19 Dashboard – {}"
